batch_size: 4
workers: 0
nepoch: 100
model_name: vrcnet_multimodal

#EXP1 feasibility experiment
#load_model: /mnt/HDD1/miruna/shape_completion/model/model_lumbar_verse20_experiment104486/best_cd_t_network_exp104486.pth

#EXP2 complete pipeline model
#load_model: /mnt/polyaxon/outputs1/miruna_gafencu/VRCNet/experiments/109114/log/vrcnet_cd_debug_2023-05-06T17:55:02/best_cd_t_network.pth
#load_model: /mnt/HDD1/miruna/shape_completion/VRCNet_trainedModels/109114/log/vrcnet_cd_debug_2023-05-06T17-55-02/best_cd_t_network.pth

# EXP3 deformation ablation model
#load_model: /mnt/polyaxon/outputs1/miruna_gafencu/VRCNet/experiments/109113/log/vrcnet_cd_debug_2023-05-06T10:58:52/best_cd_t_network.pth
#load_model: /mnt/HDD1/miruna/shape_completion/VRCNet_trainedModels/109113/log/vrcnet_cd_debug_2023-05-06T10:58:52/best_cd_t_network.pth

# EXP4 US artefacts ablation model
#load_model: /mnt/polyaxon/outputs1/miruna_gafencu/VRCNet/experiments/109249/log/vrcnet_cd_debug_2023-05-09T17:03:49/best_cd_t_network.pth
#load_model: /mnt/HDD1/miruna/shape_completion/VRCNet_trainedModels/109249/log/vrcnet_cd_debug_2023-05-09T17:03:49/best_cd_t_network.pth

# EXP5 polluted pcd ablation model
#load_model: /mnt/polyaxon/outputs1/miruna_gafencu/VRCNet/experiments/109211/log/vrcnet_cd_debug_2023-05-08T08:20:32/best_cd_t_network.pth
#load_model: /mnt/HDD1/miruna/shape_completion/VRCNet_trainedModels/109211/log/vrcnet_cd_debug_2023-05-08T08:20:32/best_cd_t_network.pth

#EXP6 patient specific network specialization
#load_model: /mnt/HDD1/miruna/shape_completion/model/patient_specific_network_specialization/patient8_specializingmodel/best_cd_t_network.pth
#load_model: /mnt/HDD1/miruna/shape_completion/model/patient_specific_network_specialization/patient6_specializingmodel/best_cd_t_network.pth
#load_model: /home/miruna_gafencu/Documents/ShapeCompletion/VRCNet/MVP_Benchmark/log/phantom_specializingmodel/best_cd_t_network.pth

#Complete pipeline
#load_model: log/vrcnet_cd_debug_2024-02-08T12:09:38/best_cd_t_network.pth
# training with the vert bodies as labelmaps

num_partial_scans_per_mesh: 1

#load_model: log/completeVertLabelmapsExperiment/best_cd_t_network.pth

path_to_train_dataset: /home/miruna/Documents/Data/Completion_Datasets/with_labelmaps_fullVert/dataset_training_fullVertlabelmaps.h5
path_to_val_dataset: /home/miruna/Documents/Data/Completion_Datasets/with_labelmaps_fullVert/dataset_validation_fullVertlabelmaps.h5
path_to_test_dataset: /home/miruna/Documents/Data/Completion_Datasets/with_labelmaps_fullVert/dataset_test_fullVertlabelmaps.h5

#name_folder_to_save_results: completeVertLabelmapsExperiment

load_model: log/vertBodyLabelmaps/best_cd_t_network.pth

#path_to_train_dataset: /home/miruna/Documents/Data/Completion_Datasets/with_labelmaps_vertbodies/dataset_training_vertBodylabelmaps.h5
#path_to_val_dataset: /home/miruna/Documents/Data/Completion_Datasets/with_labelmaps_vertbodies/dataset_validation_vertBodylabelmaps.h5
#path_to_test_dataset: /home/miruna/Documents/Data/Completion_Datasets/with_labelmaps_vertbodies/dataset_test_vertBodylabelmaps.h5
name_folder_to_save_results: test


data_to_test: test
start_epoch: 0
num_points: 4096
work_dir: log/
flag: debug
loss: cd
manual_seed: null
use_mean_feature: False
step_interval_to_print: 500
epoch_interval_to_save: 1
epoch_interval_to_val: 1
varying_constant: 0.01, 0.1, 0.5, 1
varying_constant_epochs: 5, 15, 30

lr: 0.0001
lr_decay: True
lr_decay_interval: 40
lr_decay_rate: 0.7
lr_step_decay_epochs: null
lr_step_decay_rates: null
lr_clip: 1.e-6
optimizer: Adam
weight_decay: 0
betas: 0.9, 0.999

layers: 1, 1, 1, 1
distribution_loss: KLD
knn_list: "16"
pk: 10
local_folding: True
points_label: True
num_coarse_raw: 2048
num_fps: 4096
num_coarse: 4096

apply_trafo: False
sigma: 0.005

# test
align: False
save_vis: False
eval_emd: True

use_labelmaps: True